library(rsconnect)
library(dplyr)
library(ggplot2)
library(shiny)
library(reshape2)
library(tidyverse)
library(data.table)
library(mapdata)
library(ggmap)
library(maps)
library(viridis)
library(DT)
library(plotly)
library(gganimate)
library(gifski)
library(shinycssloaders)

source("chart_1.R")
source("chart_2.R")
source("chart_3.R")


source("server.R")
source("ui.R")

shinyApp(ui = ui, server = server)
